on:
    workflow_dispatch:
        inputs:
            remote:
                description: 'Remote'
                required: true
                default: 'staging'
                type: choice
                options:
                    - staging
                    - production
            php_version:
                description: 'PHP Version'
                required: true
                default: '8.0'
                type: choice
                options:
                    - '8.1'
                    - '8.0'
                    - '7.4'
                    - '7.3'
jobs:
    unit-test:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2
            -   name: Composer install
                uses: php-actions/composer@v6
                with:
                    php_version: ${{ github.event.inputs.php_version }}
                    version: 2
                    dev: yes
                    args: "--ignore-platform-reqs"
            -   name: Run Tests
                uses: php-actions/phpunit@v3
                with:
                    configuration: ./phpunit.xml
                    memory_limit: 1024M
                env:
                    CLIENT_KEY: ${{ secrets.TEST_CLIENT_KEY }}
                    USERNAME: ${{ secrets.TEST_USERNAME }}
                    PASSWORD: ${{ secrets.TEST_PASSWORD }}
                    TEST_REMOTE: ${{ github.event.inputs.remote }}
